<form method="POST" action="<?php print $this->absoluteUrl( 'load=register&amp;do=do-password-recover' ) ?>">
	<input type="hidden" name="uid" value="<?php print $this->request['uid'] ?>" />
	<input type="hidden" name="vid" value="<?php print $this->request['vid'] ?>" />
	<input type="hidden" name="secure_token" value="<?php print $this->secureToken ?>" />
	<div class="page-section">
		<div class="section-title"><?php print $this->lang['password_change_form_title'] ?></div>
		<div class="section-content">
			<?php if ( ! empty($error) ): ?>
			<div class="warning-message"><?php print $error ?></div>
			<?php endif; ?>
			<table class="width-full">
				<tr class="row1">
					<td class="width-fourty">
						<?php print $this->lang['account_secret_question_title'] ?></td>
					<td class="width-sixty">
						<?php print $selectedQuestion ?></td>
				</tr>
				<tr class="row2">
					<td class="width-fourty">
						<?php print $this->lang['account_secret_answer_title'] ?> (<span class="help" title="<?php print $this->lang['account_secret_answer_title_help'] ?>">?</span>) <span class="require">*</span></td>
					<td class="width-sixty">
						<input type="text" name="account_secret_answer" class="input-text" /></td>
				</tr>
				<tr class="row1">
					<td class="width-fourty">
						<?php print $this->lang['new_password_field_title'] ?> <span class="require">*</span></td>
					<td class="width-sixty">
						<input type="password" name="account_password" class="input-text" /></td>
				</tr>
				<tr class="row2">
					<td class="width-fourty">
						<?php print $this->lang['new_password_confirm_field_title'] ?> <span class="require">*</span></td>
					<td class="width-sixty">
						<input type="password" name="account_password_confirmation" class="input-text" /></td>
				</tr>
			</table>
        </div>
		<div class="section-footer right">
				<input type="submit" class="input-submit" value="<?php print $this->lang['recover_password_submit'] ?>" />
		</div>
		<div class="end-page-section"></div>
	</div>
</form>