<?php $i = 0; ?>
<div class="page-section">
	<div class="section-title"><?php print $this->lang['newsletters_list_form_title'] ?></div>
	<div class="section-content">
		<?php if ( count($newsletters) > 0 ): /** Do we got any newsletters to display? **/ ?>
		<table class="width-full">
		<?php foreach ( $newsletters as $newsletter ): ?>
			<tr class="row<?php print ($i++ % 2 == 0 ? '1' : '2' ) ?>">
				<td style="width: 60%;">
					<?php print $newsletter['newsletter_name'] ?>
					<br /><div class="description"><?php print $newsletter['newsletter_description'] ?></div></td>
				<td style="width: 20%;">
				<a href="<?php print $this->absoluteUrl( 'load=newsletters&amp;do=subscribe-newsletter&amp;newsletter_id=' . $newsletter['newsletter_id'] ) ?>" class="secondary-button" title="<?php print $this->lang['subscribe_newsletter_button'] ?>"><?php print $this->lang['subscribe_newsletter_button'] ?></a>
				&nbsp;
				<a href="<?php print $this->absoluteUrl( 'load=newsletters&amp;do=unsubscribe-newsletter&amp;newsletter_id=' . $newsletter['newsletter_id'] ) ?>" class="secondary-button" title="<?php print $this->lang['remove_subscribe_newsletter_button'] ?>"><?php print $this->lang['remove_subscribe_newsletter_button'] ?></a>
			</tr>
			<?php endforeach; ?>
		</table>
		<?php else: ?>
		<div class="warning-message">
			<?php print $this->lang['no_newsletters_available_message'] ?>
		</div>
		<?php endif; ?>
	</div>
	<div class="end-page-section"></div>
</div>
<?php print $pages ?>