<?php print $newsletterData['newsletter_description'] ?>
<form method="post" action="<?php print $this->absoluteUrl( 'load=newsletters&amp;do=subscribe' ) ?>">
	<input type="hidden" name="secure_token" value="<?php print $this->secureToken ?>" />
	<input type="hidden" name="newsletter_id" value="<?php print $newsletterData['newsletter_id'] ?>" />
	<input type="text" name="subscriber_mail" class="input-text" />
	<input type="submit" class="input-submit" value="<?php print $this->lang['newsletter_subscribe_button'] ?>" />
</form>