<?php
$prevPage = intval( $data['current_value'] - $data['per_page'] );
$nextPage = intval( $data['current_value'] + $data['per_page'] );
$lastPage = intval( ( $compiledData['pages'] - 1 ) * $data['per_page'] );
?>
<div class="pagination-wrapper">
<?php if ( $compiledData['pages'] > 1 ): ?>
	<?php if ( $compiledData['current_value'] < $compiledData['pages'] ): /** We can move to the next page? **/ ?>
	<a href="<?php print $data['base_url'] . '&amp;' . $data['page_key'] . '=' . $nextPage ?>" title="<?php print $this->lang['page_next'] ?>" class="left"><?php print $this->lang['page_next'] ?></a>
	<?php endif; ?>
	<div>
	<?php if ( 1 < ($compiledData['current_value'] - $data['extended_pages']) ): /** Display the first page? **/ ?>
		<a href="<?php print $data['base_url'] . '&amp;' . $data['page_key'] . '=0' ?>" title="1">1</a>... 
	<?php endif; ?>
	<?php foreach ( $compiledData['page_numbers'] as $realPageNumber => $pageNumber ): /** Iterate on the pages **/ ?>
		<?php if ( $realPageNumber == $data['current_value'] ): /** This is the selected page? **/ ?>
		<div class="selected" title="<?php print $pageNumber ?>"><?php print $pageNumber ?></div>
		<?php else: ?>
		<a href="<?php print $data['base_url'] . '&amp;' . $data['page_key'] . '=' . $realPageNumber ?>" title="<?php print $pageNumber ?>"><?php print $pageNumber ?></a>
		<?php endif; ?>
	<?php endforeach; ?>
	<?php if ( $compiledData['use_end_dots'] === TRUE ): /** Display the last page? **/ ?>
		... <a href="<?php print $data['base_url'] . '&amp;' . $data['page_key'] . '=' . $lastPage ?>" title="<?php print $compiledData['pages'] ?>"><?php print $compiledData['pages'] ?></a>
	<?php endif; ?>
	</div>
	<?php if ( $compiledData['current_value'] > 1 ): /** We can move to the previus page? **/ ?>
	<a href="<?php print $data['base_url'] . '&amp;' . $data['page_key'] . '=' . $prevPage ?>" title="<?php print $this->lang['page_prev'] ?>"  class="right"><?php print $this->lang['page_prev'] ?></a>
	<?php endif; ?>
<?php else: ?>
	<div class="no-results">
		<?php print $this->lang['single_result'] ?>
	</div>
<?php endif; ?>
</div>