<!DOCTYPE html>
<html>
<head>
<title><?php print $this->lang['redirect'] ?></title>
<script type="text/javascript" language="javascript" src="<?php print $this->absoluteUrl( '/Client/JScripts/ThirdParty/prototype.js' ) ?>"></script>
<script type="text/javascript" language="javascript" src="<?php print $this->absoluteUrl( '/Client/JScripts/ThirdParty/scriptaculous/scriptaculous-cache.js' ) ?>"></script>
<script type="text/javascript" language="javascript" src="<?php print $this->absoluteUrl( '/Client/JScripts/PearRegistry.js' ) ?>"></script>
<script type="text/javascript" language="javascript" src="<?php print $this->absoluteUrl( '/Client/JScripts/PearMenu.js' ) ?>"></script>
<?php print $this->pearRegistry->response->getPageHeaders() ?>

<script type="text/javascript">
//<![CDATA[
	
	//=============================================================
	//	Define vars
	//=============================================================
	
	/** ##############  	Globals   ############## **/
	var PEAR_IN_DEBUG_MODE						= true;
	var PEAR_IS_ADMIN_CP							= false;
	
	/** ##############  	Member information   ############## **/
	PearRegistry.Member.memberID					= parseInt( "<?php print $this->member['member_id'] ?>" );
	PearRegistry.Member.memberName 			    = "<?php print $this->member['member_name'] ?>";
	PearRegistry.Member.memberGroup			    = parseInt( "<?php print $this->member['member_group_ids'] ?>" );
	PearRegistry.Member.isAdion			        = ( parseInt( "<?php print $this->member['group_access_cp'] ?>" ) === 1 );
	PearRegistry.Member.sessionID				= "<?php print $this->session->sessionID ?>";
	PearRegistry.Member.secureToken				= "<?php print $this->secureToken ?>";
	
	/** ##############   Urls   ############## **/
	PearRegistry.Settings.baseUrl        		= "<?php print $this->baseUrl ?>";
	PearRegistry.Settings.websiteUrl				= "<?php print $this->absoluteUrl( 'index.php' ) ?>";
	PearRegistry.Settings.uploadUrl       		= "<?php print $this->settings['upload_url'] ?>/";
	PearRegistry.Settings.imagesUrl		        = "<?php print $this->imagesUrl ?>/";

	/** ##############   Language pack  ############## **/
	PearRegistry.Settings.selectedLanguageKey	= "<?php print $this->pearRegistry->localization->selectedLanguage['language_key'] ?>";
	PearRegistry.Settings.languageIsRtl			= parseInt( "<?php print $this->pearRegistry->localization->selectedLanguage['language_is_rtl'] ?>" );
	PearRegistry.Settings.languageWeekFromSunday	= parseInt( "<?php print $this->pearRegistry->localization->selectedLanguage['language_calendar_week_from_sunday'] ?>" );
	
	/** ##############   Templates  ############## **/
	PearRegistry.Templates['loading_message']	= new Template('<div id="loading-message-layer"><img src="<?php print $this->imagesUrl ?>/loadingAnimation.gif" alt="" /> #{loadingText}</div>');
	
	//=============================================================
	//	Initialize
	//=============================================================
	
	PearRegistry.initialize();
	
//]]>
</script>
<!-- Load js language - nust become after load js classes -->
<script type="text/javascript" src="<?php print $this->absoluteUrl( '/' . PEAR_LANGUAGES_DIRECTORY . $this->pearRegistry->localization->selectedLanguage['language_key'] . '/lang_jscripts.js' )?>"></script>
</head>
<body>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<div id="redirect-screen-message">
    <div class="title">
		<?php print $this->lang['redirection_screen_title'] ?>
    </div>
	<?php print $message ?>
	<div class="center">
		<a href="<?php print $urlAddress ?>"><?php print $this->lang['redirection_screen_not_wait'] ?></a></div>
</div>
</body>
</html>