<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=<?php print $this->settings['site_charset'] ?>">
	
	<link rel="icon" href="<?php print $this->absoluteUrl( '/favicon.ico', 'cp_root' ) ?>" />
	<link rel="shortcut icon" href="<?php print $this->absoluteUrl( '/favicon.ico', 'cp_root' ) ?>" />
	<link rel="apple-touch-icon" href="<?php print $this->absoluteUrl( '/favicon.ico', 'cp_root' ) ?>" />
	
	<title><?php print $this->lang['cp_redirection_screen_page_title'] ?></title>
	<script type="text/javascript" src="<?php print $this->absoluteUrl( '/Client/JScripts/ThirdParty/prototype.js', 'site' ) ?>"></script>
	<script type="text/javascript" src="<?php print $this->absoluteUrl( '/Client/JScripts/ThirdParty/scriptaculous/scriptaculous-cache.js', 'site' ) ?>"></script>
	<script type="text/javascript" src="<?php print $this->absoluteUrl( '/Client/JScripts/PearRegistry.js', 'site') ?>"></script>
	<script type="text/javascript" src="<?php print $this->absoluteUrl( '/Client/JScripts/CP/PearCPRegistry.js', 'site' ) ?>"></script>
	<script type="text/javascript" src="<?php print $this->absoluteUrl( '/Client/JScripts/PearMenu.js', 'site' ) ?>"></script>
	<?php $this->addCSSFile('/PearCPAuth.css') ?>
	
	<?php print $this->pearRegistry->response->getPageHeaders() ?>
	
	<script type="text/javascript">
	//<![CDATA[
		
		//=============================================================
		//	Define vars
		//=============================================================
		
		/** ##############  	Globals   ############## **/
		var PEAR_IN_DEBUG_MODE						= true;
		var PEAR_IS_ADMIN_CP							= true;
		
		/** ##############  	Member information   ############## **/
		PearRegistry.Member.memberID					= parseInt( "<?php print $this->member['member_id'] ?>" );
		PearRegistry.Member.memberName 			    = "<?php print $this->member['member_name'] ?>";
		PearRegistry.Member.memberGroup			    = parseInt( "<?php print $this->member['member_group_ids'] ?>" );
		PearRegistry.Member.isAdion			        = ( parseInt( "<?php print $this->member['group_access_cp'] ?>" ) === 1 );
		PearRegistry.Member.sessionID				= "<?php print $this->session->sessionID ?>";
		PearRegistry.Member.secureToken				= "<?php print $this->secureToken ?>";
		
		/** ##############   Urls   ############## **/
		PearRegistry.Settings.baseUrl        		= "<?php print $this->baseUrl ?>";
		PearRegistry.Settings.websiteUrl				= "<?php print $this->absoluteUrl( '/index.php' ) ?>";
		PearRegistry.Settings.uploadUrl       		= "<?php print $this->settings['upload_url'] ?>/";
		PearRegistry.Settings.imagesUrl		        = "<?php print $this->imagesUrl ?>/";
	
		/** ##############   Language pack  ############## **/
		PearRegistry.Settings.selectedLanguageKey	= "<?php print $this->pearRegistry->localization->selectedLanguage['language_key'] ?>";
		PearRegistry.Settings.languageIsRtl			= parseInt( "<?php print $this->pearRegistry->localization->selectedLanguage['language_is_rtl'] ?>" );
		PearRegistry.Settings.languageWeekFromSunday	= parseInt( "<?php print $this->pearRegistry->localization->selectedLanguage['language_calendar_week_from_sunday'] ?>" );
		
		/** ##############   Templates  ############## **/
		PearRegistry.Templates['loading_message']	= new Template('<div id="loading-message-layer"><img src="<?php print $this->imagesUrl ?>/loading-animationw.gif" alt="" /> #{loadingText}</div>');
		
		//=============================================================
		//	Initialize
		//=============================================================
		
		PearRegistry.initialize();
		
	//]]>
	</script>
	
	<script type="text/javascript" src="<?php print $this->absoluteUrl( '/' . PEAR_LANGUAGES_DIRECTORY . $this->pearRegistry->localization->selectedLanguage['language_key'] . '/lang_jscripts.js', 'site' )?>"></script>
</head>
<body>
<div id="pearcp-auth-content-rect">
	<div id="pearcp-auth-header">
		<h1></h1>
	</div>
	<div class="data-block drop-shadow">
		<div class="title"><?php print $this->lang['cp_redirection_screen_form_title'] ?></div>
		<div class="content">
			<?php print  $message ?>
			<br /><br />
			<div class="center" style="font-size: 16px; font-weight: bold;">
				<a href="<?php print $urlAddress ?>"><?php print $this->lang['cp_redirection_direct_link'] ?></a>
			</div>
		</div>
	</div>
</div>
</body>
</html>