<?php
/**
 * Parameters:
 * 	Required:
 * 	- String $action:				The form URL
 *  - String $title:					The form title (display title)
 *  - Array $fields:					Array contains key-value paris to use in the form table. The key value will be used as the field descriptive text (e.g. "Site name" / "Site charset<br /><span class='description'>Here you should set your site encoding, if you don't know what this field mean, write UTF-8.</span>")
 *  									the value will be used as the field itself (although you can send whatever you want) (e.g. $this->view->textboxField('site_charset' / $this->setting['member_email'] . '<a href="">Click here to change email</a>').
 *  									If you'll set only value (which means integer key), the value will be set as colspan="2".
 *  Optional:
 * 	- String $name:					The form name [optional]
 * 	- String $id:					The form id [optional]
 *  - Array $hiddenFields:			Array contains pre-defined hidden fields to pass with the form [optional]
 *  - Array $actionsMenu:			Array contains actions for the side-menu as arrays. (e.g.: array( array('index.php?foo=bar', 'Action 1'), array('index.php?bar=baz', 'Action 2', 'add.png' ) ) [optional]
 *  - String $description:			The form description [optional]
 *	- String $submitButton:			An alternate submit button use, if not given, generating default one [optional]
 *  - String $submitButtonValue:		The text value of the DEFAULT {@see $submitButton} submit button [optional default="Save changes"]
 *  - Boolean $isMultipart:			Is this form contains multipart data (required for file uploads) [optional]
 */
?>

<form method="post" action="<?php print $this->absoluteUrl( $action ) ?>"<?php if ( $name ): ?> name="<?php print $name ?>" id="<?php print $this->escape(( ! $id ? $this->__formatElementId($name) : $id )) ?>"<?php endif; ?><?php if ( $isMultipart ): ?> enctype="multipart/form-data"<?php endif; ?>>
	<input type="hidden" name="authsession" value="<?php print $this->request['authsession'] ?>" />
	<input type="hidden" name="secure_token" value="<?php print $this->secureToken ?>" />
	<?php if ( count($hiddenFields) > 0 ): /** Do we got any hidden field to attach? **/ ?>
	<?php foreach ( $hiddenFields as $name => $value ): ?>
	<input type="hidden" name="<?php print $name ?>" value="<?php print $value ?>" />
 	<?php endforeach; ?>
	<?php endif; ?>
	
	<div class="data-block">
		<div class="title" id="PearCPTable_<?php print ++$this->tablesCount ?>">
			<?php print ( isset($this->lang[$title]) ? $this->lang[$title] : $title ) ?>
			<?php if ( count($actionsMenu) > 0 ): /** Do we got special actions? **/ ?>
				<div class="float-right">
				<?php foreach ( $actionsMenu as $i => $menu ): ?>
					<a href="<?php print $this->absoluteUrl($menu[0]) ?>">
						<?php if ( isset($menu[2]) ): /** Do we got image? **/ ?>
						<img src="Images/<?php print $menu[2] ?>" alt="" /> <?php print $menu[1] ?>
						<?php else: ?>
						<?php print $menu[1] ?>
						<?php endif; ?>
					</a>
					<?php if ( $i < (count($actionsMenu) - 1) ): ?>
					&nbsp;&middot;&nbsp;
					<?php endif; ?>
				<?php endforeach; ?>
			</div>
			<?php endif; ?>
		</div>
		<div class="content gradient"<?php if ($toggled): ?> style="display: none;"<?php endif; ?>>
			<?php if ( ! empty($description) ): ?>
			<div class="information-message"><?php print ( isset($this->lang[$description]) ? $this->lang[$description] : $description ) ?></div>
			<?php endif; ?>
			<table id="PearCP_Table_<?php print $this->tablesCount ?>" class="gradient-table width-full">
			<?php foreach ( $fields as $descriptive => $field ): ?>
				<tr class="row<?php print ($i++ % 2 == 0 ? 1 : 2) ?>">
					<?php if (! is_int($descriptive) ): /** 2 colspan? **/ ?>
					<td class="width-fourty">
						<?php print ( isset($this->lang[$descriptive]) ? $this->lang[$descriptive] : $descriptive) ?></td>
					<td class="width-sixty">
						<?php print ( isset($this->lang[$field]) ? $this->lang[$field] : $field) ?></td>
					<?php else: ?>
					<td class="width-full" colspan="2">
						<?php print ( isset($this->lang[$field]) ? $this->lang[$field] : $field) ?></td>
					<?php endif; ?>
				</tr>
			<?php endforeach; ?>
				<tr class="row<?php print ($i++ % 2 == 0 ? 1 : 2) ?>">
					<td class="width-full" colspan="2">
						<div class="right" style="padding: 3px;">
							<?php if (! empty($submitButton) ): ?>
							<?php print $submitButton ?>
							<?php elseif ( is_array($submitButtonValue) ): ?>
							<?php foreach ( $submitButtonValue as $buttonName => $buttonValue ): ?>
							<input type="submit" name="<?php if (! $buttonName): ?>PearCPTable_<?php print $this->tablesCount ?>_Submit<?php else: print $buttonName; endif; ?>" id="<?php if (! $buttonName): ?>PearCPTable_<?php print $this->tablesCount ?>_Submit<?php else: print $buttonName; endif; ?>" value="<?php print ( ! empty($buttonValue) ? ( isset($this->lang[$buttonValue]) ? $this->lang[$buttonValue] : $buttonValue ) : $this->lang['save_changes'] ) ?>" class="input-submit" />
							<?php endforeach; ?>
							<?php else: ?>
							<input type="submit" name="PearCPTable_<?php print $this->tablesCount ?>_Submit" id="PearCPTable_<?php print $this->tablesCount ?>_Submit" value="<?php print ( ! empty($submitButtonValue) ? ( isset($this->lang[$submitButtonValue]) ? $this->lang[$submitButtonValue] : $submitButtonValue ) : $this->lang['save_changes'] ) ?>" class="input-submit" />
							<?php endif; ?>
						</div>
					</td>
				</tr>
			</table>
		</div>
	</div>
</form>