<?php
/**
 * Parameters:
 * 	Required:
 * 	- String $action:				The form URL
 *  - Array $groups:					Array contains the tabs groups to create, each item key is the tab strip value and each value is array that contains data about the tab.
 *  									The array values items is just as the standardForm.phtml $fields array (title, description, fields) {@see standardForm.phtml}
 *  Optional:
 * 	- String $name:					The form name [optional]
 * 	- String $id:					The form id [optional]
 *  - String $tabsControlName:		The tabs control name [optional]
 *  - Array $hiddenFields:			Array contains pre-defined hidden fields to pass with the form [optional]
 *  - Integer $selectedTab:			The selected tab, if not specified, using the first tab [optional default="1"]
 *	- String $submitButton:			An alternate submit button use, if not given, generating default one [optional]
 *  - String $submitButtonValue:		The text value of the DEFAULT {@see $submitButton} submit button [optional default="Save changes"]
 *  - Boolean $isMultipart:			Is this form contains multipart data (required for file uploads) [optional]
 */

$tabsControlName = ( $tabsControlName ? $tabsControlName : microtime() );
?>

<?php $this->addJSFile( '/PearUITabs.js' ) ?>
<form method="post" action="<?php print $this->absoluteUrl( $action ) ?>"<?php if ( $name ): ?> name="<?php print $name ?>" id="<?php print $this->escape(( ! $id ? $this->__formatElementId($name) : $id )) ?>"<?php endif; ?><?php if ( $isMultipart ): ?> enctype="multipart/form-data"<?php endif; ?>>
	<input type="hidden" name="authsession" value="<?php print $this->request['authsession'] ?>" />
	<input type="hidden" name="secure_token" value="<?php print $this->secureToken ?>" />
	<?php if ( count($hiddenFields) > 0 ): /** Do we got any hidden field to attach? **/ ?>
	<?php foreach ( $hiddenFields as $name => $value ): ?>
	<input type="hidden" name="<?php print $name ?>" value="<?php print $value ?>" />
 	<?php endforeach; ?>
	<?php endif; ?>
	
	<div class="data-block">
		<ul class="pearcp-tabs-wrapper" id="<?php print $tabsControlName ?>_TabStrip">
		<?php foreach ( array_keys($groups) as $tabStripTitle ): ?>
			<li><?php print ( isset($this->lang[$tabStripTitle]) ? $this->lang[$tabStripTitle] : $tabStripTitle ) ?></li>
		<?php endforeach; ?>
		</ul>
		<div class="pearcp-tabs-content" id="<?php print $tabsControlName ?>_PaneWrapper">
			<?php foreach ( array_values($groups) as $i => $pane ): ?>
			<div id="<?php print $tabsControlName ?>-<?php print ($i + 1) ?>">
				<div class="title">
					<?php print $pane['title'] ?>
				</div>
				<div class="content gradient">
					<?php if ( ! empty($pane['description']) ): ?>
					<div class="information-message"><?php print $pane['description'] ?></div>
					<?php endif; ?>
					<table class="gradient-table">
					<?php foreach ( $pane['fields'] as $descriptive => $field ): ?>
						<tr class="row<?php print ($i++ % 2 == 0 ? 1 : 2) ?>">
							<?php if (! is_int($descriptive) ): /** 2 colspan? **/ ?>
							<td class="width-fourty">
								<?php print ( isset($this->lang[$descriptive]) ? $this->lang[$descriptive] : $descriptive) ?></td>
							<td class="width-sixty">
								<?php print ( isset($this->lang[$field]) ? $this->lang[$field] : $field) ?></td>
							<?php else: ?>
							<td class="width-full" colspan="2">
								<?php print ( isset($this->lang[$field]) ? $this->lang[$field] : $field) ?></td>
							<?php endif; ?>
						</tr>
					<?php endforeach; ?>
					</table>
				</div>
			</div>
			<?php endforeach; ?>
		</div>
		<div class="actions-bar">
			<div class="right" style="padding: 3px;">
				<?php if (! empty($submitButton) ): ?>
				<?php print $submitButton ?>
				<?php elseif ( is_array($submitButtonValue) ): ?>
				<?php foreach ( $submitButtonValue as $buttonName => $buttonValue ): ?>
				<input type="submit" name="<?php if (! $buttonName): ?>PearCPTable_<?php print $this->tablesCount ?>_Submit<?php else: print $buttonName; endif; ?>" id="<?php if (! $buttonName): ?>PearCPTable_<?php print $this->tablesCount ?>_Submit<?php else: print $buttonName; endif; ?>" value="<?php print ( ! empty($buttonValue) ? ( isset($this->lang[$buttonValue]) ? $this->lang[$buttonValue] : $buttonValue ) : $this->lang['save_changes'] ) ?>" class="input-submit" />
				<?php endforeach; ?>
				<?php else: ?>
				<input type="submit" name="PearCPTable_<?php print $this->tablesCount ?>_Submit" id="PearCPTable_<?php print $this->tablesCount ?>_Submit" value="<?php print ( ! empty($submitButtonValue) ? ( isset($this->lang[$submitButtonValue]) ? $this->lang[$submitButtonValue] : $submitButtonValue ) : $this->lang['save_changes'] ) ?>" class="input-submit" />
				<?php endif; ?>
			</div>
		</div>
	</div>
</form>
<script type="text/javascript">
//<![CDATA[
	new PearUITabs('<?php print $tabsControlName ?>', <?php print ( intval($selectedTab) > 0 ? $selectedTab : 1) ?>, { effectType: "opacity", duration: 0.5 });
//]]>
</script>