<form method="post" action="<?php print $this->absoluteUrl( 'load=usercp&amp;do=save-avatar' ) ?>"  enctype="multipart/form-data">
<input type="hidden" name="secure_token" value="<?php print $this->secureToken ?>" />
<div class="page-section">
	<div class="section-title">
		<?php print $this->lang['change_avatar_form_title'] ?>
		<div class="dropdown_list_head float-right" id="usercp_actions_menu_head">
				<?php print $this->lang['usercp_actions_list_head'] ?></div>
    		</div>
	<div class="section-content">
		<div class="center">
			<img src="<?php print $this->member['member_avatar'] ?>" alt="" style="width: <?php print $this->member['avatar_sizes']['width'] ?>px; height: <?php print $this->member['avatar_sizes']['height'] ?>px;" /><br />
			<?php if ( $this->member['member_avatar_can_be_removed'] ): ?>
			<a href="<?php print $this->absoluteUrl( 'load=usercp&amp;do=remove-avatar&amp;t=' . $this->secureToken ) ?>"><?php print $this->lang['remove_avatar_link'] ?></a>
			<?php endif; ?>
		</div>
		<br />
		<div class="information-message">
			<?php print $this->lang['change_avatar_information'] ?>
		</div>
		<table class="width-full">
			<tr class="row1">
				<td class="width-fourty">
					<?php print $this->lang['change_avatar_url_field'] ?></td>
				<td class="width-sixty">
					<input type="text" class="input-text" name="member_avatar_url" /></td>
			</tr>
			<tr class="row2">
				<td class="width-fourty">
					<?php print $this->lang['change_avatar_upload_field'] ?></td>
				<td class="width-sixty">
					<input type="file" class="input-text" name="FILE_UPLOAD" /></td>
			</tr>
		</table>
		<div class="actions-bar">
			<div class="right">
				<input type="submit" value="<?php print $this->lang['save_avatar_button'] ?>" class="input-submit" /></div>
			<div class="clear"></div>
		</div>
	</div>
</div>
</form>
<div class="dropdown_menu_wrapper" id="usercp_actions_menu">
	<div class="title"><?php print $this->lang['usercp_actions_list_head'] ?></div>
	<a href="<?php print $this->absoluteUrl( 'load=usercp&amp;do=dashboard' ) ?>"><?php print $this->lang['view_dashboard_action'] ?></a>
	<a href="<?php print $this->absoluteUrl( 'load=usercp&amp;do=personal-information' ) ?>"><?php print $this->lang['change_personal_details_action'] ?></a>
	<a href="<?php print $this->absoluteUrl( 'load=usercp&amp;do=change-name' ) ?>"><?php print $this->lang['change_email_details_action'] ?></a>
	<a href="<?php print $this->absoluteUrl( 'load=usercp&amp;do=change-password' ) ?>"><?php print $this->lang['change_password_details_action'] ?></a>
	<a href="<?php print $this->absoluteUrl( 'load=usercp&amp;do=modify-avatar' ) ?>"><?php print $this->lang['change_avatar_action'] ?></a>
</div>
<script type="text/javascript">
//<![CDATA[
	PearRegistry.Menus.register( new PearMenu( 'usercp_actions_menu_head', 'usercp_actions_menu' ) );
//]]>
</script>