<form method="post" action="<?php print $this->absoluteUrl( 'load=usercp&amp;do=save-name' ) ?>">
<input type="hidden" name="secure_token" value="<?php print $this->secureToken ?>" />		
<div class="page-section">
	<div class="section-title">
		<?php print $this->lang['change_names_form_title'] ?>
			<div class="dropdown_list_head float-right" id="usercp_actions_menu_head">
				<?php print $this->lang['usercp_actions_list_head'] ?></div>
    		</div>
	<div class="section-content">
		<?php print $error ?>
		<div class="information-message">
			<?php print $this->lang['change_names_information'] ?></div>
		<table class="width-full">
			<tr class="row1">
				<td class="width-fourty">
					<?php print $this->lang['change_names_account_name_field'] ?></td>
				<td class="width-sixty">
					<input type="text" class="input-text" name="account_name" value="<?php print $this->member['member_name'] ?>" /></td>
			<tr class="row2">
				<td class="width-fourty">
					<?php print $this->lang['change_names_account_email_field'] ?></td>
				<td class="width-sixty">
					<input type="text" class="input-text" name="account_email" value="<?php print $this->member['member_email'] ?>" /></td>
			</tr>
			<tr class="row1">
				<td class="width-fourty">
					<?php print $this->lang['change_names_account_current_password_field'] ?></td>
				<td class="width-sixty">
					<input type="password" class="input-text" name="account_pass" /></td>
			</tr>
		</table>
		<div class="actions-bar">
			<div class="right">
				<input type="submit" value="<?php print $this->lang['save_names_button'] ?>" class="input-submit" /></div>
			<div class="clear"></div>
		</div>
	</div>
</div>
</form>
<div class="dropdown_menu_wrapper" id="usercp_actions_menu">
	<div class="title"><?php print $this->lang['usercp_actions_list_head'] ?></div>
	<a href="<?php print $this->absoluteUrl( 'load=usercp&amp;do=dashboard' ) ?>"><?php print $this->lang['view_dashboard_action'] ?></a>
	<a href="<?php print $this->absoluteUrl( 'load=usercp&amp;do=personal-information' ) ?>"><?php print $this->lang['change_personal_details_action'] ?></a>
	<a href="<?php print $this->absoluteUrl( 'load=usercp&amp;do=change-name' ) ?>"><?php print $this->lang['change_email_details_action'] ?></a>
	<a href="<?php print $this->absoluteUrl( 'load=usercp&amp;do=change-password' ) ?>"><?php print $this->lang['change_password_details_action'] ?></a>
	<a href="<?php print $this->absoluteUrl( 'load=usercp&amp;do=modify-avatar' ) ?>"><?php print $this->lang['change_avatar_action'] ?></a>
</div>
<script type="text/javascript">
//<![CDATA[
	PearRegistry.Menus.register( new PearMenu( 'usercp_actions_menu_head', 'usercp_actions_menu' ) );
//]]>
</script>