<?php $this->addJSFile('/Site/Pear.UserCP.js') ?>
<form method="post" action="<?php print $this->absoluteUrl( 'load=usercp&amp;do=save-password' ) ?>">
<input type="hidden" name="secure_token" value="<?php print $this->secureToken ?>" />		
<div class="page-section">
	<div class="section-title">
		<?php print $this->lang['change_passwords_page_title'] ?>
			<div class="dropdown_list_head float-right" id="usercp_actions_menu_head">
				<?php print $this->lang['usercp_actions_list_head'] ?></div>
    		</div>
	<div class="section-content">
		<?php print $error ?>
		<div class="information-message">
			<?php print $this->lang['change_passwords_information'] ?></div>
		<table class="width-full">
			<tr class="row1">
				<td class="width-fourty">
					<?php print $this->lang['change_passwords_secret_question_field'] ?></td>
				<td class="width-sixty">
					<select name="secret_question" id="secret_question">
					<?php foreach ( $questions as $id => $title): ?>
					<option value="<?php print $id ?>"><?php print $title ?></option>
					<?php endforeach; ?>
					<option value="0"><?php print $this->lang['write_own_secret_question'] ?></option>
				</select>
				<div id="custom_secret_question">
					<input type="text" name="custom_secret_question" value="<?php print $this->request['custom_secret_question'] ?>" class="input-text" />
				</div></td>
			<tr class="row2">
				<td class="width-fourty">
					<?php print $this->lang['change_passwords_secret_answer_field'] ?></td>
				<td class="width-sixty">
					<input type="text" class="input-text" name="secret_answer" /></td>
			</tr>
			<tr class="row1">
				<td class="width-fourty">
					<?php print $this->lang['change_passwords_new_pass'] ?></td>
				<td class="width-sixty">
					<input type="password" class="input-text" name="account_new_pass" /></td>
			</tr>
			<tr class="row2">
				<td class="width-fourty">
					<?php print $this->lang['change_passwords_new_pass_confim'] ?></td>
				<td class="width-sixty">
					<input type="password" class="input-text" name="account_confirm_pass" /></td>
			</tr>
			<tr class="row1">
				<td class="width-fourty">
					<?php print $this->lang['change_names_account_current_password_field'] ?></td>
				<td class="width-sixty">
					<input type="password" class="input-text" name="account_pass" /></td>
			</tr>
		</table>
		<div class="actions-bar">
			<div class="right">
				<input type="submit" value="<?php print $this->lang['save_passwords_button'] ?>" class="input-submit" /></div>
			<div class="clear"></div>
		</div>
	</div>
</div>
</form>
<div class="dropdown_menu_wrapper" id="usercp_actions_menu">
	<div class="title"><?php print $this->lang['usercp_actions_list_head'] ?></div>
	<a href="<?php print $this->absoluteUrl( 'load=usercp&amp;do=dashboard' ) ?>"><?php print $this->lang['view_dashboard_action'] ?></a>
	<a href="<?php print $this->absoluteUrl( 'load=usercp&amp;do=personal-information' ) ?>"><?php print $this->lang['change_personal_details_action'] ?></a>
	<a href="<?php print $this->absoluteUrl( 'load=usercp&amp;do=change-name' ) ?>"><?php print $this->lang['change_email_details_action'] ?></a>
	<a href="<?php print $this->absoluteUrl( 'load=usercp&amp;do=change-password' ) ?>"><?php print $this->lang['change_password_details_action'] ?></a>
	<a href="<?php print $this->absoluteUrl( 'load=usercp&amp;do=modify-avatar' ) ?>"><?php print $this->lang['change_avatar_action'] ?></a>
</div>
<script type="text/javascript">
//<![CDATA[

	PearRegistry.Menus.register( new PearMenu( 'usercp_actions_menu_head', 'usercp_actions_menu' ) );
	PearUserCPUtils.initialize();

//]]>
</script>