<form method="post" action="<?php print $this->absoluteUrl( 'load=usercp&amp;do=save-personal-information' ) ?>">
<input type="hidden" name="secure_token" value="<?php print $this->secureToken ?>" />		
<div class="page-section">
	<div class="section-title">
		<?php print $this->lang['general_information_form_title'] ?>
			<div class="dropdown_list_head float-right" id="usercp_actions_menu_head">
				<?php print $this->lang['usercp_actions_list_head'] ?></div>
    	</div>
	<div class="section-content">
		<table class="width-full">
			<tr class="row1">
				<td class="width-fourty">
					<?php print $this->lang['member_first_name'] ?></td>
				<td class="width-sixty">
					<input type="text" class="input-text" name="member_first_name" value="<?php print $this->member['member_first_name'] ?>" /></td>
			</tr>
			<tr class="row2">
				<td class="width-fourty">
					<?php print $this->lang['member_last_name'] ?></td>
				<td class="width-sixty">
					<input type="text" class="input-text" name="member_last_name" value="<?php print $this->member['member_last_name'] ?>" /></td>
			</tr>
			<tr class="row1">
				<td class="width-fourty">
					<?php print $this->lang['member_bday'] ?></td>
				<td class="width-sixty">
					<select name="member_bday_year" class="input-select">
						<optgroup label="<?php print $this->lang['year'] ?>">
						<?php foreach (range((intval(date('Y')) - 100), date('Y')) as $year): ?>
							<?php if ($this->member['_member_bday']['year'] == $year): /** This is the member birth year? **/ ?>
							<option value="<?php print $year ?>" selected="selected"><?php print $year ?></option>
							<?php else: ?>
							<option value="<?php print $year ?>"><?php print $year ?></option>
							<?php endif; ?>
						<?php endforeach; ?>
						</optgroup>
					</select> /
					<?php if ( $this->pearRegistry->localization->selectedLanguage['language_calendar_week_from_sunday'] ): /** What to set first? the day or month selector? **/ ?>
					<select name="member_bday_month" class="input-select">
						<optgroup label="<?php print $this->lang['month'] ?>">
						<?php foreach (range(1, 12) as $month): ?>
							<?php if ($this->member['_member_bday']['mon'] == $month): /** This is the member birth month? **/ ?>
							<option value="<?php print $month ?>" selected="selected"><?php print $month ?></option>
							<?php else: ?>
							<option value="<?php print $month ?>"><?php print $month ?></option>
							<?php endif; ?>
						<?php endforeach; ?>
						</optgroup>
					</select> / 
					<select name="member_bday_day" class="input-select">
						<optgroup label="<?php print $this->lang['day'] ?>">
						<?php foreach (range(1, 31) as $day): ?>
							<?php if ($this->member['_member_bday']['mday'] == $day): /** This is the member birth day (not birthday, the day itself, LOL)? **/ ?>
							<option value="<?php print $day ?>" selected="selected"><?php print $day ?></option>
							<?php else: ?>
							<option value="<?php print $day ?>"><?php print $day ?></option>
							<?php endif; ?>
						<?php endforeach; ?>
						</optgroup>
					</select>
					<?php else: ?>
					<select name="member_bday_day" class="input-select">
						<optgroup label="<?php print $this->lang['day'] ?>">
						<?php foreach (range(1, 31) as $day): ?>
							<?php if ($this->member['_member_bday']['mday'] == $day): /** This is the member birth day (not birthday, the day itself, LOL)? **/ ?>
							<option value="<?php print $day ?>" selected="selected"><?php print $day ?></option>
							<?php else: ?>
							<option value="<?php print $day ?>"><?php print $day ?></option>
							<?php endif; ?>
						<?php endforeach; ?>
						</optgroup>
					</select> / 
					<select name="member_bday_month" class="input-select">
						<optgroup label="<?php print $this->lang['month'] ?>">
						<?php foreach (range(1, 12) as $month): ?>
							<?php if ($this->member['_member_bday']['mon'] == $month): /** This is the member birth month? **/ ?>
							<option value="<?php print $month ?>" selected="selected"><?php print $month ?></option>
							<?php else: ?>
							<option value="<?php print $month ?>"><?php print $month ?></option>
							<?php endif; ?>
						<?php endforeach; ?>
						</optgroup>
					</select>
					<?php endif; ?>
				</td>
			</tr>
			<tr class="row2">
				<td class="width-fourty">
					<?php print $this->lang['member_gender_field'] ?></td>
				<td class="width-sixty">
					<select name="member_gender" class="input-select">
					<?php foreach (array('mystery', 'male', 'female') as $value => $gender): ?>
						<option value="<?php print $value ?>" <?php if ( $this->member['member_gender'] == $value ): ?>selected="selected"<?php endif; ?>><?php print $this->lang['gender_' . $gender ] ?></option>
					<?php endforeach; ?>
					</select></td>
			</tr>
			<tr class="row1">
				<td class="width-fourty">
					<?php print $this->lang['member_street_address'] ?></td>
				<td class="width-sixty">
					<input type="text" class="input-text" name="member_street_address" value="<?php print $this->member['member_street_address'] ?>" /></td>
			</tr>
			<tr class="row2">
				<td class="width-fourty">
					<?php print $this->lang['member_postal_code'] ?></td>
				<td class="width-sixty">
					<input type="text" class="input-text" name="member_postal_code" value="<?php print $this->member['member_postal_code'] ?>" /></td>
			</tr>
			<tr class="row1">
				<td class="width-fourty">
					<?php print $this->lang['member_phone'] ?></td>
				<td class="width-sixty">
					<input type="text" class="input-text" name="member_phone" value="<?php print $this->member['member_phone'] ?>" /></td>
			</tr>
			<tr class="row2">
				<td class="width-fourty">
					<?php print $this->lang['member_mobile_phone'] ?></td>
				<td class="width-sixty">
					<input type="text" class="input-text" name="member_mobile_phone" value="<?php print $this->member['member_mobile_phone'] ?>" /></td>
			</tr>
			<tr class="row1">
				<td class="width-fourty">
					<?php print $this->lang['general_information_allow_admin_mails'] ?></td>
				<td class="width-sixty">
					<input type="checkbox" name="member_allow_admin_mails" value="1" <?php if ( $this->member['member_allow_admin_mails'] ): ?>checked="checked"<?php endif; ?> /></td>
			</tr>
			<tr class="row2">
				<td class="width-fourty">
					<?php print $this->lang['general_information_timezone'] ?></td>
				<td class="width-sixty">
					<select name="time_offset" class="input-select">
						<?php print $timezoneSelection ?>
					</select></td>
			</tr>
			<tr class="row1">
				<td class="width-fourty">
					<?php print $this->lang['member_website_address'] ?></td>
				<td class="width-sixty">
					<input type="text" class="input-text" name="member_website_address" value="<?php print $this->member['member_website_address'] ?>" /></td>
			</tr>
			<tr class="row2">
				<td class="width-fourty">
					<?php print $this->lang['general_information_dst_in_use'] ?></td>
				<td class="width-sixty">
					<input type="checkbox" name="dst_in_use" value="1" <?php print $this->member['dst_in_use__ui'] ?> />
			</tr>
			<tr class="row1">
				<td class="width-fourty">
					<?php print $this->lang['contact_information_email_field'] ?></td>
				<td class="width-sixty">
					<input type="text" class="input-text" disabled="disabled" value="<?php print $this->member['member_email'] ?>" /> &middot; <a href="<?php print $this->absoluteUrl( 'load=usercp&amp;do=change-name' ) ?>"><?php print $this->lang['contact_information_email_change'] ?></a></td>
			</tr>
			<tr class="row2">
				<td class="width-fourty">
					<?php print $this->lang['contact_information_icq_field'] ?></td>
				<td class="width-sixty">
					<input type="text" class="input-text" name="member_icq" value="<?php print $this->member['member_icq'] ?>" /></td>
			</tr>
			<tr class="row1">
				<td class="width-fourty">
					<?php print $this->lang['contact_information_msn_field'] ?></td>
				<td class="width-sixty">
					<input type="text" class="input-text" name="member_msn" value="<?php print $this->member['member_msn'] ?>" /></td>
			</tr>
			<tr class="row2">
				<td class="width-fourty">
					<?php print $this->lang['contact_information_skype_field'] ?></td>
				<td class="width-sixty">
					<input type="text" class="input-text" name="member_skype" value="<?php print $this->member['member_aim'] ?>" /></td>
			</tr>
			<tr class="row1">
				<td class="width-fourty">
					<?php print $this->lang['contact_information_aim_field'] ?></td>
				<td class="width-sixty">
					<input type="text" class="input-text" name="member_aim" value="<?php print $this->member['member_skype'] ?>" /></td>
			</tr>
		</table>
		<div class="actions-bar">
			<div class="right">
				<input type="submit" value="<?php print $this->lang['save_personal_information_button'] ?>" class="input-submit" /></div>
			<div class="clear"></div>
		</div>
	</div>
</div>
</form>
<div class="dropdown_menu_wrapper" id="usercp_actions_menu">
	<div class="title"><?php print $this->lang['usercp_actions_list_head'] ?></div>
	<a href="<?php print $this->absoluteUrl( 'load=usercp&amp;do=dashboard' ) ?>"><?php print $this->lang['view_dashboard_action'] ?></a>
	<a href="<?php print $this->absoluteUrl( 'load=usercp&amp;do=personal-information' ) ?>"><?php print $this->lang['change_personal_details_action'] ?></a>
	<a href="<?php print $this->absoluteUrl( 'load=usercp&amp;do=change-name' ) ?>"><?php print $this->lang['change_email_details_action'] ?></a>
	<a href="<?php print $this->absoluteUrl( 'load=usercp&amp;do=change-password' ) ?>"><?php print $this->lang['change_password_details_action'] ?></a>
	<a href="<?php print $this->absoluteUrl( 'load=usercp&amp;do=modify-avatar' ) ?>"><?php print $this->lang['change_avatar_action'] ?></a>
</div>
<script type="text/javascript">
//<![CDATA[
	PearRegistry.Menus.register( new PearMenu( 'usercp_actions_menu_head', 'usercp_actions_menu' ) );
//]]>
</script>