<!DOCTYPE html>
<html>
<head>
	<title><?php print $this->lang['auth_form_page_title'] ?></title>
	<script type="text/javascript" src="<?php print $this->absoluteUrl( '/Client/JScripts/ThirdParty/prototype.js', 'site' ) ?>"></script>
	<script type="text/javascript" src="<?php print $this->absoluteUrl( '/Client/JScripts/ThirdParty/scriptaculous/scriptaculous-cache.js', 'site' ) ?>"></script>
	<script type="text/javascript" src="<?php print $this->absoluteUrl( '/Client/JScripts/PearRegistry.js', 'site') ?>"></script>
	<script type="text/javascript" src="<?php print $this->absoluteUrl( '/Client/JScripts/CP/PearCPRegistry.js', 'site' ) ?>"></script>
	<script type="text/javascript" src="<?php print $this->absoluteUrl( '/Client/JScripts/PearMenu.js', 'site' ) ?>"></script>
	<?php $this->addCSSFile('/PearCPAuth.css') ?>
	<?php print $this->pearRegistry->response->getPageHeaders() ?>
	
	<script type="text/javascript">
	//<![CDATA[
		
		//=============================================================
		//	Define vars
		//=============================================================
		
		/** ##############  	Globals   ############## **/
		var PEAR_IN_DEBUG_MODE						= true;
		var PEAR_IS_ADMIN_CP							= true;
		
		/** ##############  	Member information   ############## **/
		PearRegistry.Member.memberID					= parseInt( "<?php print $this->member['member_id'] ?>" );
		PearRegistry.Member.memberName 			    = "<?php print $this->member['member_name'] ?>";
		PearRegistry.Member.memberGroup			    = parseInt( "<?php print $this->member['member_group_ids'] ?>" );
		PearRegistry.Member.isAdion			        = ( parseInt( "<?php print $this->member['group_access_cp'] ?>" ) === 1 );
		PearRegistry.Member.sessionID				= "<?php print $this->session->sessionID ?>";
		PearRegistry.Member.secureToken				= "<?php print $this->secureToken ?>";
		
		/** ##############   Urls   ############## **/
		PearRegistry.Settings.baseUrl        		= "<?php print $this->baseUrl ?>";
		PearRegistry.Settings.websiteUrl				= "<?php print $this->absoluteUrl( 'index.php' ) ?>";
		PearRegistry.Settings.uploadUrl       		= "<?php print $this->settings['upload_url'] ?>/";
		PearRegistry.Settings.imagesUrl		        = "<?php print $this->imagesUrl ?>/";
	
		/** ##############   Language pack  ############## **/
		PearRegistry.Settings.selectedLanguageKey	= "<?php print $this->pearRegistry->localization->selectedLanguage['language_key'] ?>";
		PearRegistry.Settings.languageIsRtl			= parseInt( "<?php print $this->pearRegistry->localization->selectedLanguage['language_is_rtl'] ?>" );
		
		/** ##############   Templates  ############## **/
		PearRegistry.Templates['loading_message']	= new Template('<div id="loading-message-layer"><img src="<?php print $this->imagesUrl ?>/loading-animation.gif" alt="" /> #{loadingText}</div>');
		
		//=============================================================
		//	Initialize
		//=============================================================
		
		PearRegistry.initialize();
		
	//]]>
	</script>
	
	<script type="text/javascript" src="<?php print $this->absoluteUrl( PEAR_LANGUAGES_DIRECTORY . $this->pearRegistry->localization->selectedLanguage['language_key'] . '/lang_jscripts.js', 'site' )?>"></script>
</head>
<body>
<div id="pearcp-auth-content-rect">
	<div id="pearcp-auth-header">
		<h1></h1>
	</div>
	<div class="data-block drop-shadow">
		<div class="title"><?php print $this->lang['auth_center_form_title'] ?></div>
		<div class="content">
			<?php if (! empty($message) ): ?>
			<div class="warning-message"><?php print ( isset($this->lang[$message]) ? $this->lang[$message] : $message ) ?></div>
			<?php endif; ?>
			<form method="post" action="<?php print $this->pearRegistry->admin->rootUrl ?>index.php?load=authentication&amp;do=do-auth">
			<input type="hidden" name="secure_token" value="<?php print $this->secureToken ?>" />
			<input type="hidden" name="query_string" value="<?php print $queryString ?>" />
				<table class="width-full">
					<tr>
						<td>
							<table class="width-full">
								<tr>
									<td class="width-fourty">
										<img src="./Images/Authentication/member-email.png" alt="" /> <?php print $this->lang['member_email'] ?></td>
									<td class="width-sixty">
										<input type="text" style="width: 250px;" name="member_email" id="member_email" class="input-text" value="<?php print $memberEmail ?>" placeholder="<?php print $this->lang['member_email'] ?>" /></td>
								</tr>
								<tr>
									<td class="width-fourty">
										<img src="./Images/Authentication/member-pass.png" alt="" /> <?php print $this->lang['member_password'] ?></td>
									<td class="width-sixty">
										<input type="password" style="width: 250px;" class="input-text" name="member_password" id="member_password" placeholder="<?php print $this->lang['member_password'] ?>" /></td>
								</tr>
								<?php if ( intval($this->settings['admincp_auth_use_passcode']) AND $this->pearRegistry->isMD5($this->settings['admincp_auth_passcode']) ): /** Can we use ACP passcode? **/ ?>
								<tr>
									<td class="width-fourty">
										<?php print $this->lang['auth_form_passcode_field_title'] ?> (<span class="help" title="<?php print $this->lang['auth_form_passcode_field_help'] ?>">?</span>)</td>
									<td class="width-sixty">
										<input type="password" class="input-text" name="admincp_auth_passcode" placeholder="<?php print $this->lang['auth_form_passcode_field_title'] ?>" /></td>
								</tr>
								<?php endif; ?>
		            				<?php if ( intval($this->settings['admincp_auth_use_captcha']) ): /** Can we use captcha validation **/ ?>
		            				<tr>
									<td class="width-full" colspan="2">
										<div style="margin-top: 3px; margin-bottom: 3px;"><img src="<?php print $this->absoluteUrl('load=authentication&amp;do=display-captcha') ?>" /></div></td>
								</tr>
								<tr>
									<td class="width-fourty">
										<?php print $this->lang['captcha_validation_field_title'] ?> (<span class="help" title="<?php print $this->lang['captcha_validation_field_desc'] ?>">?</span>)</td>
									<td class="width-sixty">
										<input type="text" class="input-text" name="captcha_validation" id="captcha_validation" placeholder="<?php print $this->lang['captcha_validation_field_title'] ?>" /></td>
								</tr>
		            				<?php endif; ?>
		            			</table>
						</td>
						<td>
							<input type="hidden" name="query_string" value="<?php print $queryString ?>" />
							<input type="submit" value="<?php print $this->lang['auth_center_submit'] ?>" />
						</td>
					</tr>
				</table>
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">
//<![CDATA[
	$( "<?php print $focusAtTextbox ?>" ).focus();
//]]>
</script>
</body>
</html>