<form method="POST" action="<?php print $this->absoluteUrl( 'load=login&amp;do=do-recover-password' ) ?>">
	<input type="hidden" name="page_referer" value="<?php print $this->request['page_referer'] ?>" />
	<div class="page-section">
		<div class="section-title"><?php print $this->lang['password_recover_form_title'] ?></div>
		<div class="section-content">
			<?php if(! empty($error) ): ?>
			<div class="warning-message"><?php print $error ?></div>
			<?php endif; ?>
			<table class="width-full">
				<tr>
					<td class="width-sixty">
						<?php print $this->lang['email_or_user_field_title'] ?></td>
					<td class="width-fourty">
						<input type="text" class="input-text" name="account_identifier" value="<?php print $this->request['account_identifier'] ?>" /></td>
				</tr>
				<tr>
					<td class="width-sixty">
						<?php print $this->lang['captcha_image_field_title'] ?></td>
					<td class="width-fourty">
						<img src="<?php print $this->absoluteUrl( 'load=login&amp;do=captcha-image' ) ?>" alt="" />
						<input type="text" class="input-text" name="captcha_validation" value="" /></td>
				</tr>
			</table>
		</div>
		<div class="section-footer right">
			<input type="submit" class="input-submit" value="<?php print $this->lang['recover_password_submit'] ?>" />
		</div>
		<div class="end-page-section"></div>
	</div>
</form>