<form method="post" action="<?php print $this->absoluteUrl('load=content&amp;do=input-password&amp;directory_id=' . $data['directory_id'] . '&amp;page_id=' . $data['page_id'] ) ?>">
<input type="hidden" name="secure_token" value="<?php print $this->secureToken ?>" />
<div class="page-section">
	<div class="section-title"><?php print $formTitle ?></div>
	<div class="section-content">
		<?php if (! empty($error) ): ?>
		<div class="warning-message"><?php print $error ?></div>
		<?php endif; ?>
		<div class="information-message"><?php print $formDescription ?></div>
		<table class="width-full">
			<tr class="row1">
				<td class="width-fourty">
					<?php print $this->lang['password_input_field'] ?></td>
				<td class="width-sixty">
					<input type="password" class="input-text" name="password_input" /></td>
			</tr>
			<tr class="row2">
				<td class="width-fourty">
					<?php print $this->lang['password_remember_field'] ?></td>
				<td class="width-sixty">
					<input type="checkbox" name="remeber_password" value="1" /></td>
			</tr>
		</table>
		<div class="actions-bar">
			<div class="right">
				<input type="submit" class="input-submit" value="<?php print $this->lang['enter_password_submit'] ?>" /></div>
			<div class="clear"></div>
		</div>
	</div>
</div>
</form>