<p>
	<?php printf($this->lang['step_done_instructions'], str_replace('https:/', 'http:/', $this->pearRegistry->siteBaseUrl), $this->pearRegistry->adminCPUrl) ?>
</p>
<p>
	<?php print $this->lang['useful_links_title'] ?>
</p>
<ul class="links-list">
	<li><a href="http://quartz-technologies.com"><?php print $this->lang['pearti_site'] ?></a></li>
	<li><a href="http://pearcms.com"><?php print $this->lang['pearcms_site'] ?></a></li>
	<li><a href="http://community.pearcms.com"><?php print $this->lang['pearcms_support_community'] ?></a></li>
	<li><a href="mailto:support@pearcms.com"><?php print $this->lang['generatl_qanda_mail'] ?></a></li>
	<li><a href="mailto:root@quartz-technologies.com"><?php print $this->lang['company_management_mail'] ?></a></li>
	<li><a href="mailto:info@pearcms.com"><?php print $this->lang['general_info_mail']?> </a></li>
	<li><a href="mailto:accuonts@pearcms.com"><?php print $this->lang['accounts_info_mail'] ?></a></li>
</ul>
<p>
	<?php print $this->lang['step_done_greeting'] ?>
</p>